server:
 port: 8091
 error:
  include-binding-errors: always
  include-message: always
  include-stacktrace: never
spring:
 datasource:
    url: jdbc:mysql://localhost:3306/realestate_db
    username: root
    password: Lcvrt.3992
    driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL8Dialect
   properties:
      '[hibernate.format_sql]': true
logging:
 file:
  name: log/realestate.log
 pattern:
  file: "%d %-5level [%thread] %logger:%msg%n"
 level:
  '[org.springframework.web]' : WARN
  '[org.hibernate]' : INFO
  '[org.realestate]' : DEBUG
management: #actuator
 endpoints:
  web:
   exposure:
    include: '*'
 info:
  env:
   enabled: true
 endpoint:
  health:
   show-details: always
  shutdown:
   enabled: true
realestate:
 app:
  jwtSecret: realEstate@!23
  jwtExpirationMs: 86400000 
info:
 application:
  name: 'RealEstate Backend App'
  description: 'This is RealEstate Property Backend Project'
  version: '@project.version@'
